name: Build and Publish Void IDE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, x86]
    steps:
    - uses: actions/checkout@v3
      with:
        repository: build1
        path: build1

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for Linux (${{ matrix.arch }})
      run: |
        cd build1
        npm ci
        npm run gulp -- vscode-linux-${{ matrix.arch }}

    - name: Package artifacts
      run: |
        mkdir -p dist
        tar -czf dist/build1-void-linux-${{ matrix.arch }}.tar.gz -C build1/build/linux-${{ matrix.arch }} .

    - name: Publish to GitHub Packages
      uses: actions/upload-artifact@v3
      with:
        name: build1-void-linux-${{ matrix.arch }}
        path: dist/build1-void-linux-${{ matrix.arch }}.tar.gz
