name: Build for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.17.0'
        cache: 'npm'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libkrb5-dev \
          libgssapi-krb5-2 \
          python3 \
          make \
          g++

    - name: Install npm dependencies
      run: |
        npm install
        npm install --save-dev @types/react

    - name: Prebuild steps
      run: |
        npm run postinstall || true
        npm run compile || true

    - name: Build for Linux
      run: |
        npm run gulp vscode-linux-x64 --verbose

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vscode-linux-x64
        path: .build/linux/
        retention-days: 5

    - name: Diagnostic Information
      if: failure()
      run: |
        echo "Node.js version:"
        node --version
        echo "npm version:"
        npm --version
        echo "Listing node_modules:"
        ls -la node_modules
        echo "Checking React-related modules:"
        find . -name "react" -type d
